name: FD Backfill 2024-2025

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Remove old DB
        run: rm -f data/football.db

      - name: Ingest Football-Data
        run: python -u scripts/fd_ingest.py

      - name: Build ELO history
        run: python -u scripts/build_elo_history.py

      - name: Compute method stats
        run: python -u scripts/odds_method_stats.py

      - name: Generate predictions
        run: python -u scripts/generate_predictions.py

      - name: Export predictions (last 7 days)
        run: |
          mkdir -p predictions
          python -u scripts/export_predictions.py --days 7

      - name: Commit updated DB & predictions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Backfill 2024-2025 completed [skip ci]" || echo "No changes"
          git push
