name: Daily Fixtures & Predictions

on:
  schedule:
    - cron: "0 8 * * *"   # Tous les jours à 08:00 UTC
  workflow_dispatch:       # Lancer manuellement si besoin

permissions:
  contents: write

jobs:
  fetch_and_predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      # 1) Récupère les matchs du jour (API-Football via RapidAPI)
      - name: Fetch today's fixtures (API-Football)
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python -u scripts/fetch_today.py

      # 2) Recalcule l'ELO après éventuelles MAJ de résultats
      - name: Build ELO history
        run: python -u scripts/build_elo_history.py

      # 3) Migration: crée la table 'odds' si manquante (évite l'erreur "no such table: odds")
      - name: Create odds table if missing
        run: python -u scripts/migrate_add_odds.py

      # 4) Génère les prédictions du jour (ELO / Bookmakers / Combined)
      - name: Generate predictions (today)
        run: python -u scripts/generate_predictions.py

      # 5) Exporte les prédictions (jour courant)
      - name: Export predictions (today)
        run: |
          mkdir -p predictions
          python -u scripts/export_predictions.py --days 1

      # 6) Commit & push de la DB et des fichiers exportés
      - name: Commit & Push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Daily fixtures & predictions update [skip ci]" || echo "No changes"
          git push
