name: Daily Fixtures & Predictions

on:
  schedule:
    - cron: "0 8 * * *"   # Tous les jours à 08:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch_predict:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data dir
        run: mkdir -p data

      # 🔧 Migration anti "datatype mismatch" : team_stats.team_id devient TEXT
      - name: Migrate team_stats.team_id to TEXT
        run: python -u scripts/migrate_team_stats_text.py

      # 🧲 Récupère les fixtures du jour via API-Football et les insère dans la DB
      - name: Fetch today's fixtures (API-Football)
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python -u scripts/fetch_today.py

      # ♟️ Recalcule l'ELO (au cas où des résultats aient évolué)
      - name: Build ELO history
        run: python -u scripts/build_elo_history.py

      # 🧮 Génère les prédictions du jour (ELO / B365 / PINNACLE / COMBINED)
      - name: Generate predictions (today)
        run: python -u scripts/generate_predictions.py

      # 📤 Exporte les fichiers CSV pour aujourd'hui (et fallback si vide)
      - name: Export predictions (today)
        run: |
          mkdir -p predictions
          python -u scripts/export_predictions.py --days 1

      # 💾 Commit & push de la DB et des fichiers d'export
      - name: Commit & Push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Daily fixtures & predictions update [skip ci]" || echo "No changes"
          git push
