name: Daily Fixtures & Predictions

on:
  schedule:
    - cron: "0 8 * * *"  # Tous les jours à 08:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch_and_predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      # Récupère le code et autorise le push (commit DB + fichiers exportés)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      # --- Migrations (idempotentes) ---
      - name: Ensure matches schema is complete
        run: python -u scripts/migrate_matches_schema.py

      - name: Create odds table if missing
        run: python -u scripts/migrate_add_odds.py

      - name: Migrate team_stats schema
        run: python -u scripts/migrate_team_stats_schema.py

      # --- Récupération fixtures du jour depuis API-Football ---
      - name: Fetch today's fixtures (API-Football)
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python -u scripts/fetch_today.py

      # --- Rebuild Elo (si résultats tombés) ---
      - name: Build ELO history (refresh after new results)
        run: python -u scripts/build_elo_history.py

      # --- Génération des prédictions du jour ---
      - name: Generate predictions (today)
        run: python -u scripts/generate_predictions.py

      # --- Export des prédictions du jour ---
      - name: Export predictions (today)
        run: |
          mkdir -p predictions
          python -u scripts/export_predictions.py --days 1

      # --- Commit & Push des mises à jour ---
      - name: Commit & Push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Daily fixtures & predictions update [skip ci]" || echo "No changes"
          git push
